import { jsPDF } from 'jspdf'

export interface DoctorReport {
  chiefComplaint: string
  urgencyLevel: string
  symptoms: string[]
  duration: string
  possibleConsiderations: string[]
  conditionToExclude: string
  suggestedNextSteps: string[]
  redFlags: string[]
  summary: string
}

/**
 * Renders the AI-generated intake summary as a simple, doctor-legible PDF
 * and triggers a browser download. Deliberately plain (no external assets) —
 * this is a pre-consultation aid, not a formal medical document.
 */
export function downloadDoctorReportPdf(report: DoctorReport, languageLabel: string) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const marginX = 48
  const pageWidth = doc.internal.pageSize.getWidth()
  const contentWidth = pageWidth - marginX * 2
  let y = 56

  const ensureSpace = (needed: number) => {
    const pageHeight = doc.internal.pageSize.getHeight()
    if (y + needed > pageHeight - 48) {
      doc.addPage()
      y = 56
    }
  }

  const writeHeading = (text: string) => {
    ensureSpace(28)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(12.5)
    doc.text(text, marginX, y)
    y += 18
  }

  const writeParagraph = (text: string) => {
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10.5)
    const lines = doc.splitTextToSize(text, contentWidth)
    ensureSpace(lines.length * 14 + 8)
    doc.text(lines, marginX, y)
    y += lines.length * 14 + 10
  }

  const writeBullets = (items: string[]) => {
    if (items.length === 0) {
      writeParagraph('— none reported —')
      return
    }
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10.5)
    for (const item of items) {
      const lines = doc.splitTextToSize(`•  ${item}`, contentWidth - 8)
      ensureSpace(lines.length * 14 + 2)
      doc.text(lines, marginX, y)
      y += lines.length * 14 + 2
    }
    y += 8
  }

  // Header
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(17)
  doc.text('G1 — Pre-Consultation Summary', marginX, y)
  y += 20
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9.5)
  doc.setTextColor(110)
  const generated = new Date().toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' })
  doc.text(`Generated ${generated} · Conversation language: ${languageLabel}`, marginX, y)
  doc.setTextColor(0)
  y += 18
  if (report.urgencyLevel) {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(10.5)
    doc.text(`Urgency: ${report.urgencyLevel}`, marginX, y)
    y += 16
  }
  doc.setDrawColor(210)
  doc.line(marginX, y, pageWidth - marginX, y)
  y += 24

  writeHeading('Chief Complaint')
  writeParagraph(report.chiefComplaint || 'Not specified')

  writeHeading('Duration')
  writeParagraph(report.duration || 'Not specified')

  writeHeading('Reported Symptoms')
  writeBullets(report.symptoms)

  writeHeading('Possible Considerations')
  writeBullets(report.possibleConsiderations)

  if (report.conditionToExclude) {
    writeHeading('Important Condition to Exclude')
    writeParagraph(report.conditionToExclude)
  }

  writeHeading('Suggested Next Steps')
  writeBullets(report.suggestedNextSteps)

  writeHeading('Seek Urgent Care If')
  writeBullets(report.redFlags)

  writeHeading('Summary')
  writeParagraph(report.summary || '')

  ensureSpace(60)
  doc.setDrawColor(210)
  doc.line(marginX, y, pageWidth - marginX, y)
  y += 16
  doc.setFont('helvetica', 'italic')
  doc.setFontSize(8.5)
  doc.setTextColor(120)
  const disclaimer = doc.splitTextToSize(
    'Generated by G1, an AI health assistant, based only on what the patient described in chat. This is not a diagnosis and is intended solely to help a licensed doctor quickly understand the context before an in-person consultation.',
    contentWidth,
  )
  doc.text(disclaimer, marginX, y)

  doc.save(`g1-doctor-report-${Date.now()}.pdf`)
}
