import { Download, X } from 'lucide-react'
import type { DoctorReport } from '@/lib/report'
import { downloadDoctorReportPdf } from '@/lib/report'

interface Props {
  report: DoctorReport
  languageLabel: string
  onClose: () => void
}

/** Interactive in-page view of the same structured report api/report.ts already
 * generates for the text chat — reused as-is, just presented with an urgency
 * badge and expandable-feeling sections instead of going straight to a PDF. */
export function VoiceReportModal({ report, languageLabel, onClose }: Props) {
  const urgencyTone = report.urgencyLevel?.toLowerCase().includes('emergency')
    ? 'bg-tint-rose/15 text-tint-rose border-tint-rose/30'
    : report.urgencyLevel?.toLowerCase().includes('same-day')
      ? 'bg-tint-amber/20 text-fg border-tint-amber/40'
      : 'bg-accent/10 text-fg border-accent/30'

  return (
    <div className="fixed inset-0 z-[60] flex items-center justify-center bg-ink/40 p-4 backdrop-blur-sm">
      <div className="glass-card flex max-h-[85vh] w-full max-w-md flex-col overflow-hidden rounded-[26px] border border-white/20 bg-surface/95 backdrop-blur-2xl">
        <div className="flex items-center gap-2 border-b border-border px-4 py-3">
          <h2 className="font-display text-[14px] font-black text-fg">Doctor Report</h2>
          <button type="button" onClick={onClose} aria-label="Close" className="ml-auto flex size-7 items-center justify-center rounded-full text-fg-muted hover:text-fg">
            <X className="size-4" strokeWidth={2.5} />
          </button>
        </div>

        <div data-lenis-prevent className="flex-1 space-y-4 overflow-y-auto p-4">
          {report.urgencyLevel && (
            <span className={`inline-block rounded-full border px-3 py-1 text-[11px] font-black ${urgencyTone}`}>
              {report.urgencyLevel}
            </span>
          )}

          <Section title="Chief Complaint" text={report.chiefComplaint} />
          <Section title="Duration" text={report.duration} />
          <BulletSection title="Symptoms" items={report.symptoms} />
          <BulletSection title="Possible Considerations" items={report.possibleConsiderations} />
          {report.conditionToExclude && <Section title="Important Condition to Exclude" text={report.conditionToExclude} />}
          <BulletSection title="Suggested Next Steps" items={report.suggestedNextSteps} />
          <BulletSection title="Seek Urgent Care If" items={report.redFlags} />
          <Section title="Summary" text={report.summary} />

          <p className="pt-1 text-[10px] leading-relaxed text-fg-muted">
            Generated by G1, based only on what was said in this conversation. Not a diagnosis — for a licensed
            doctor's review before treatment.
          </p>
        </div>

        <div className="border-t border-border p-3">
          <button
            type="button"
            onClick={() => downloadDoctorReportPdf(report, languageLabel)}
            className="flex w-full items-center justify-center gap-2 rounded-full bg-accent py-2.5 text-[13px] font-black text-accent-fg"
          >
            <Download className="size-3.5" strokeWidth={2.5} />
            Download PDF
          </button>
        </div>
      </div>
    </div>
  )
}

function Section({ title, text }: { title: string; text: string }) {
  if (!text) return null
  return (
    <div>
      <h3 className="mb-1 text-[10px] font-black tracking-wide text-fg-muted uppercase">{title}</h3>
      <p className="text-[12.5px] leading-relaxed text-fg">{text}</p>
    </div>
  )
}

function BulletSection({ title, items }: { title: string; items: string[] }) {
  if (!items || items.length === 0) return null
  return (
    <div>
      <h3 className="mb-1 text-[10px] font-black tracking-wide text-fg-muted uppercase">{title}</h3>
      <ul className="space-y-1">
        {items.map((item, i) => (
          <li key={i} className="text-[12.5px] leading-relaxed text-fg">
            • {item}
          </li>
        ))}
      </ul>
    </div>
  )
}
